### ISSUE TITLE
KEDW

### ISSUE THREAD

**Issue by nealjha** [IF-Apps/IF-Charts#13]
Would be nice to see this major Air Force base :)

**Comment by GiacomoLaw** [comment]
Not sure about this one.... it might come after I have more space with hosting. 😄

**Comment by GiacomoLaw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [KEDW](https://trello.com/c/IhhzTq2p/8-kedw)

**Comment by GiacomoLaw** [comment]
Military airport, charts not public. 😢

**Comment by GiacomoLaw** [comment]
C-130 is out, this airport may get a little more busy. Will see how much space the charts take up, and then add them according to that.

**Comment by GiacomoLaw** [comment]
Looking at adding this now. We will see what people want.

**Comment by GiacomoLaw** [comment]
Not much intrest, so closing again. If enough people want it, I will reopen and add.
