### ISSUE TITLE
KDFW

### ISSUE THREAD

**Issue by Mix56awesome** [IF-Apps/IF-Charts#16]
You should add KDFW.

**Comment by GiacomoLaw** [comment]
@Mix56awesome Thanks for requesting! May I ask what region this is in? 😄

**Comment by Mix56awesome** [comment]
This airport is in Northern Texas

⁣​

**Comment by GiacomoLaw** [comment]
@Mix56awesome It should be added after the release of global 😄

**Comment by Mix56awesome** [comment]
Awesome thank you for adding this airport on your list. Hopefully it's one of the first ones done when global comes out 😉

⁣

Sent from BlueMail

​

**Comment by GiacomoLaw** [comment]
No problem! 👍

**Comment by GiacomoLaw** [comment]
Doing this now. 😄

**Comment by Mix56awesome** [comment]
Thank you, this is going to be great for global 😁

⁣Sent from BlueMail ​
