### ISSUE TITLE
PHOG

### ISSUE THREAD

**Issue by dushyants19** [IF-Apps/IF-Charts#42]
Kahului - OCG|PHOG

Hawaii region

**Comment by GiacomoLaw** [comment]
Will do!

**Comment by GiacomoLaw** [comment]
Uploading it now!

**Comment by GiacomoLaw** [comment]
https://github.com/IF-Apps/IF-Charts/commit/782247be44c69257842c2a14582fe54d1019dab1

Added! Enjoy. 😄
