### ISSUE TITLE
KRIL

### ISSUE THREAD

**Issue by dushyants19** [IF-Apps/IF-Charts#53]
Garfield County Regional Airport

**Comment by GiacomoLaw** [comment]
Not sure about this one, it is a regional airport... 😕

**Comment by GiacomoLaw** [comment]
@dushyants19 Is it currently in IF?

**Comment by GiacomoLaw** [comment]
Sorry, not going to be added. It's a small airport, plus it's not in IF yet... 😢

**Comment by dushyants19** [comment]
It's in IF

**Comment by GiacomoLaw** [comment]
Okay, cool. But I can't add it as it is very small.
